const jwt = require('jsonwebtoken')
require('dotenv').config()

let Authenticate = (req, res, next) => {

    // finding user from request path
    let slices = req.path.split('/')
    const req_user = slices[2]

    // all users
    const users = ['admin', 'professor', 'librarian', 'student']
    const user = users.find(element => {
        if (req_user == element)
        return element
    })

    const header = req.headers['authorization']
    
    if (typeof header !== undefined) {
        const bearer = header.split(' ')
        const token = bearer[1]

        // token verification
        const data = jwt.verify(token, process.env.JWT_KEY)

        if (data) {
            // checks token generated by Admin
            if (data.role.toLowerCase() == user )
                next()
            else res.json({ status: false, message: `Protected route. Only ${user} access` })
        }
        else res.json({ status: false, message: 'Request Token Expired' })
    }
    else res.status(403).json({ status: false, message: 'request Token not found' })
}

module.exports = Authenticate